// Implements TEST_PLAN.md Section G: React Syntax Highlighter Integration Validation
import { generateDateHash } from '../support/utils';

describe('React Syntax Highlighter Integration Validation (Section G)', () => {
  it('creates Lesson 2000 with a Python code block and verifies syntax highlighting (Test Case 11)', () => {
    cy.signedInSession('editor');
    cy.deleteLessonIfExists('/cs/scratch1A', '2000');
    cy.visit('/cs/scratch1A');

    const lessonTitle = generateDateHash('Syntax and Blocks Integration Test');
    const contentHash = generateDateHash('import-random-hash');
    const pythonCode = `
# Content Hash: ${contentHash}
import random

def battle_ready(pokemon):
    hp = random.randint(50, 100)
    print(pokemon + " is ready with " + str(hp) + " HP!")
`;

    const fullContent = `This is an integration test for syntax highlighting.\n\n\`\`\`python${pythonCode}\`\`\``;

    // 1. Add New Lesson
    cy.contains('button', 'Add New Lesson').click();
    cy.get('.modal-dialog').first().should('be.visible');

    cy.get('.modal-dialog').first().find('input[type="number"]').type('2000');
    cy.get('.modal-dialog').first().find('input[placeholder="Lesson title"]').type(lessonTitle);
    cy.get('#content-textarea').type(fullContent);
    cy.get('.modal-dialog').first().contains('button', 'Save').click();

    // 2. Click the Lesson 2000 link from the list
    cy.contains('.lesson-link', `Lesson 2000: ${lessonTitle}`).should('be.visible').click();
    cy.url().should('include', '/cs/scratch1A/lesson/2000');

    // 3. Assertions on Syntax Highlighter rendering
    // Verify the code block is rendered inside a pre element with syntax highlighting spans
    cy.get('.curriculum-content').find('pre code').should('be.visible');
    cy.get('.curriculum-content')
      .find('pre code')
      .should('contain', `Content Hash: ${contentHash}`);
    cy.get('.curriculum-content').find('pre code').should('contain', 'import random');
    cy.get('.curriculum-content').find('pre code').should('contain', 'def battle_ready');
    cy.get('.curriculum-content').find('pre code').should('contain', 'print');

    // Verify token spans are generated by react-syntax-highlighter
    cy.get('.curriculum-content').find('pre code span').should('have.length.at.least', 5);

    // Cleanup: Delete Lesson 2000
    cy.contains('button', 'Edit Lesson').click();
    cy.get('.modal-dialog').first().should('be.visible');

    let confirmVal = true;
    cy.on('window:confirm', () => {
      return confirmVal;
    });
    cy.then(() => {
      confirmVal = true;
    });
    cy.get('.modal-dialog').first().contains('button', 'Delete').click();

    // Verify redirection and removal
    cy.url().should('eq', Cypress.config().baseUrl + '/cs/scratch1A');
    cy.contains('.lesson-link', `Lesson 2000: ${lessonTitle}`).should('not.exist');
  });
});
